### ISSUE TITLE
release-0.0.4 Linux x64 crash to desktop

### ISSUE THREAD

**Issue by adwiz** [LanetNetwork/kodi-addons#1]
after installation and attempts to enable TV option in settings Kodi crashes to desktop
[here's logfile](http://pastebin.com/ByCFZpBu) with debug mode on
thanks

**Comment by cryol** [comment]
preduschee discussion: [here](https://cryol.kiev.ua/2015/01/282/)

```
23:45:21 T:140266316724160   DEBUG: ADDON: cpluff: 'Plug-in pvr.lanet.tv-isengard has been installed.'
```

plugin reinstalled from cache.

remove from cache

```
/home/username/.kodi/addons/packages/
```

and plugin dir

```
/home/username/.kodi/addons/pvr.lanet.tv-isengard
```

after remove - install from [this zip](https://github.com/LanetNetwork/kodi-addons/raw/gh-pages/repository.lanet.ua/pvr.lanettv-isengard/pvr.lanettv-isengard-0.0.4.zip)

**Comment by adwiz** [comment]
removed plugin from cache and addons folders, removed old logs
installing .zip from your link and the same thing here...
new logs:
[kodi.log](http://pastebin.com/pbD3AMV3)
[kodi_crashlog-20150902_120401.log](http://pastebin.com/mSsXw0gp)

**Comment by cryol** [comment]
try latest update : 5d01743f3549973aed38058f5bd0e0bf38784816
zip: 5d04795d545867076c5a7402726fc9652f515d7b

**Comment by adwiz** [comment]
it seems work fine with latest update
think issue closed
thanks a ton!
